blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/orgs/realworld-angular/discussions
    about: Have a question or want to discuss something?
  - name: RealWorld Angular starter repository
    url: https://github.com/realworld-angular/realworld-angular-starter
    about: Issues and feature requests for the Angular starter repository
